# Generated by Django 3.2.11 on 2022-01-17 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='disabled',
            field=models.BooleanField(default=False),
        ),
    ]
