# Generated by Django 3.2.11 on 2022-01-10 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Ent', 'Ent'), ('Hello', 'Hello'), ('Hi', 'Hi')], default='Ent', max_length=500),
            preserve_default=False,
        ),
    ]
