# Generated by Django 3.2.11 on 2022-01-11 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('Entertaintment', 'Entertaintment'), ('Hello', 'Hello'), ('Hi', 'Hi')], max_length=500),
        ),
    ]
