# Generated by Django 3.2.11 on 2022-01-18 14:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0010_alter_bookmark_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='todayspick',
            name='picked_till_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
